# Medidas Resumo

Prezados, nesta parte vocês encontram alguns exercícios relacionados ao tópico de medidas resumo onde aprendemos a calcular média e mediana. Além disso, aqui será tratado o tópico sobre desvio padrão, uma medida também vista.

Lembrando que vocês podem encontrar esse tópico no capítulo 3 do livro @estatistica_anderson_2013, um dos livros que temos como referência para a nossa disciplina[^medidas_resumo_01-1].

[^medidas_resumo_01-1]: Na versão que tenho, a sessão na qual podem estudar contém o seguinte título: *Medidas de Posição*, para o tópico de médias e medianas; *Medidas de Variabilidade*, que trata do desvio padrão; e *Média ponderada e o trabalho com dados agrupados*, que explica e exemplifica o conceito de média ponderada.

------------------------------------------------------------------------

**Exercício 1:** O conjunto de dados mostrados abaixo indica as diferentes previsões feitas por analistas de mercado sobre os rumos da economia, previsões para o PIB - Produto Interno Bruto.

| 2,6     | 3,1     | 2,3     | 2,7     | 3,4     | 0,9     | 2,6     | 2,8     | 2,0     | 2,4     |
|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|
| **2,7** | **2,7** | **2,7** | **2,9** | **3,1** | **2,8** | **1,7** | **2,3** | **2,8** | **3,5** |
| **0,4** | **2,5** | **2,2** | **1,9** | **1,8** | **1,1** | **2,0** | **2,1** | **2,5** | **0,5** |

A partir dos dados acima você deverá calcular a média e a mediada.

**Exercício 2:** Os dados mostrados abaixo são referentes aos prazos de entregas de duas empresas transportadoras, *Rápida* e *Super Rápida*.

Rápida: 11, 10, 9, 10, 11, 11, 10, 11, 10 e 10

Super Rápida: 8, 10, 13 ,7 ,10, 11, 10, 7, 15 e 12

Calcule o desvio padrão do tempo de entregas para cada empresa. Com base no cálculo feito, qual delas você escolheria para receber um produto?

**Exercício 3:** Um jogador é contratado por um time e ao final de dez rodadas o técnico quer fazer uma análise sobre o seu desempenho médio. Para isso, atribui pesos de acordo com a dificuldade do adversário que o jogador enfrentou. Abaixo são mostradas as rodadas (R) e quantidades de gols marcados de acordo com o peso do advesário:

Rodada (R) e gols marcados contra adversários com dificuldade igual a 1: *R1* = 4 gol; *R3* = 2 gols; *R5* = 3 gol; *R6* = 3 gols e *R9* = 3 gols;

Rodada (R) e gols marcados contra adversários com dificuldade igual a 3: *R2* = 0 gols; *R4* = 1 gol; *R7* = 0 gols; *R8* = 1 gol e *R10* = 0 gols;

Compare o desempenho desse jogador por meio de uma média simples de gols e a média que leve em conta a dificuldade do adversário. O que você acha do desempenho desse jogador?

As respostas dos exercícios acima podem ser encontradas [aqui](/respostas/respostas_medidas_resumo.qmd)
