# Tabelas: Variáveis Quantitativas

Dando sequência aos exercícios sobre como representar dados por meio de tabelas, vamos nesta parte trabalhar com variáveis que possuem valores do tipo quantitativo. Vocês devem lembrar que a representação de dados quantitativos exige a necessidade de criamos classes nas quais vamos associar os valores, classes essas que poderão ser informadas diretamente no problema ou deverão ser construídas.

Esse conteúdo vocês poderão também encontrar no capítulo 2 do livro @estatistica_anderson_2013, um dos livros que temos como referência para a nossa disciplina.[^tabelas_frequencia_02-1]

[^tabelas_frequencia_02-1]: Na versão que tenho, um pouco mais antiga, a sessão na qual podem estudar contém o seguinte título: *Sintetizando os dados quantitativos*, mas pelo que notei em versões mais novas, o título da sessão também se mantém o mesmo.

------------------------------------------------------------------------

**Exercício 1:** Com base nas toneladas de carga transportadas em um ano, os portos enumerados a seguir são os 25 mais movimentados nos Estados Unidos (The 2013 World Almanac):

|    **Porto**    | **Toneladas Transportadas (milhões)** |    **Porto**    | **Toneladas Transportadas (milhões)** |
|:---------------:|:------------------:|:---------------:|:------------------:|
|    Baltimore    |                 39,6                  | Norfolk Harbor  |                 41,6                  |
|   Baton Rouge   |                 55,5                  |   Pascagoula    |                 37,3                  |
|    Beaumont     |                 77,0                  |  Philadelphia   |                 34,0                  |
| Corpus Christi  |                 73,7                  |   Pittsburgh    |                 33,8                  |
| Duluth-Superior |                 36,6                  |   Plaquemines   |                 55,8                  |
|     Houston     |                 227,1                 |   Port Arthur   |                 30,2                  |
|   Huntington    |                 61,5                  |    Savannah     |                 34,7                  |
|  Lake Charles   |                 54,6                  | South Louisiana |                 236,3                 |
|   Long Beach    |                 75,4                  |    St. Louis    |                 30,8                  |
|   Los Angeles   |                 62,4                  |      Tampa      |                 34,2                  |
|     Mobile      |                 55,7                  |   Texas City    |                 56,6                  |
|   New Orleans   |                 72,4                  |     Valdez      |                 31,9                  |
|    New York     |                 139,2                 |                 |                                       |

Pede-se:

1.  Qual é o maior número de toneladas transportadas? Qual é o menor número de toneladas transportadas?
2.  Utilizando a amplitude de classes de 25, desenvolva uma distruibuição de frequências dos dados começando com 25-49.9;50-79.9; e assim por diante. Obs.: *Você deve considerar todos os tipos de frequências construídos em aula, incluindo as acumuladas!;*
3.  Apenas construa os intervalos de classes segundo o critério de Sturges e compare com as classes sugeridas acima[^tabelas_frequencia_02-2].

[^tabelas_frequencia_02-2]: Lembrando que por meio desse critério precisamos primeiramente identificar o número de classes $(k)$, dado por meio da seguinte fórmula: $k = 1 + 3,3\times\log(n)$ , com $n$ sendo o tamanho de nossa amostra. Posteriormente ao cálculo das classes, podemos identificar o tamanho do intervalo/amplitude das classes $(h)$ por meio da equação $h=\frac{A}{k}$, onde $A$ é a amplitude dos dados.

**Exercício 2:** A London School of Economics e a Harvard Business School conduziram um estudo de como os diretores executivos (CEOs) passam seu dia. O estudo descobriu que os CEOs gastam, em média, cerca de 18 horas por semana em reuniões, não incluindo conferências on-line, almoços executivos e eventos públicos (The Wall Street Journal, 14 de fevereiro de 2012). Abaixo é apresentado o tempo gasto por semana em reuniões (horas) para uma amostra de 25 CEOs.

|     |     |     |     |     |
|:---:|:---:|:---:|:---:|:---:|
| 21  | 18  | 23  | 20  | 12  |
| 23  | 15  | 16  | 19  | 18  |
| 14  | 15  | 21  | 20  | 19  |
| 15  | 23  | 15  | 22  | 23  |
| 19  | 18  | 13  | 21  | 15  |

Pede-se:

1.  Utilize uma amplitude de classe de duas horas para preparar uma distribuição de frequência: absoluta, relativa, absoluta acumulada e relativa acumulada;
2.  Construa as classes segundo o método visto em aula e compare com as que você construiu no item anterior verificando a existência de diferença entre as duas.

**Exercício 3:** A revista Entrepreneur classifica franquias que utilizam medidas de desempenho tais como taxa de crescimento, número de pontos de venda, custos iniciais e estabilidade financeira. O número de pontos de venda referentes às 20 principais franquias nos Estados Unidos estão a seguir (The World Almanac, 2012).

| Franchise                      | Quantidade |
|:-------------------------------|:----------:|
| Hampton Inns                   |   1.864    |
| ampm                           |   3.183    |
| McDonald's                     |   32.805   |
| 7-Eleven Inc.                  |   37.496   |
| Supercuts                      |   2.130    |
| Days Inn                       |   1.877    |
| Vanguard Cleaning Systems      |   2.155    |
| Servpro                        |   1.572    |
| Subway                         |   34.871   |
| Denny's Inc.                   |   1.668    |
| Jan-Pro Franchising Intl. Inc. |   12.394   |
| Hardee's                       |   1.901    |
| Pizza Hut Inc.                 |   13.281   |
| Kumon Math & Reading Centers   |   25.199   |
| Dunkin Donuts                  |   9.947    |
| KFC Corp.                      |   16.224   |
| Jazzercise Inc.                |   7.683    |
| Anytime Fitness                |   1.618    |
| Matco Tools                    |   1.431    |
| Stratus Building Solutions     |   5.018    |

Pede-se:

1.  Utilize as classes 0-4.999, 5.000-9.999, 10.000-14.999, e assim por diante para encontrar as frequências da variável quantitativa;
2.  Suponha que as classes acima não tivessem sido dadas, construa essas classes por meio do método visto em aula.


As respostas dos exercícios acima podem ser encontradas [aqui](/respostas/respostas_quantitativas.qmd)
